---
- name: azure  
  hosts: localhost
  connection: local
  gather_facts: false

  tasks: 
    - name: getresourcegroupinfo
      azure.azcollection.azure_rm_resourcegroup_info:
        name: rg_ansible
      register: rginfo

    - name: debug
      debug: 
        var: rginfo  
