---
- name: azure  
  hosts: localhost
  connection: local
  gather_facts: false

  tasks: 
    - name: get ad app info ---- by App ID
      azure.azcollection.azure_rm_adapplication_info:
        app_id: "{{ '64bfd223-1b6f-4960-be9d-d7ac5e4b1d91' }}"
        tenant: "{{ '0be2e53a-a3a6-4735-aa09-99972743714c' }}"
